package com.subway.utils.autoCode;

import freemarker.template.TemplateException;

import java.io.IOException;
import java.sql.SQLException;


public class AutoGenerationDemo {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException,TemplateException {
        //数据库地址
        String url = "jdbc:mysql://localhost:3306/gscms";
        //用户名
        String name = "root";
        //密码
        String passWord = "beijingsubway2017@";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "t_operate_log";
        //模板路径
        String templateDir = "F:\\template";
        //生成文件路径
        String autoGeneratedFile = "E:\\dev\\gscms\\src\\main\\java\\com\\subway\\autoCode";
        //实例化
        AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir);
        
        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
    }

}
